{
	"data": "ENC[AES256_GCM,data:0ME/GtsA3Xgflm7g3D2VUPboG4gvtHlwtEGpatAqn+gNGR+KORbxWjG2eB37DM7UnusGnJIu5vNu2GKGhdc/2mi0cKK0wm71EIkLNlFV5LgVGMAWoOPPwByzE8skjfB/+QuXIGilzww7dVCUs+tIcfSdeWHRUD9MvQMEISsNTUhyIS6nIi16qiHKfgZdnsjW4E8515uxL43Xsd96J5c7evlbFHItwl8gvHC6vWdp5QMXiEZ+9siRnDyeaGpqRg==,iv:6jom+9Sexks1ae87CeHKbndYaaPsigcy2jRurfTCD4Q=,tag:BEnybaAvjbPuLXOvI3VBNA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1754ys0a08mn327kwthprlzlfkuj2fx3vhpeghcy2p2g632s83fyqxljf90",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbUpuSEkxR3JjalFybnFB\nbG44OGNDS1NTZ05xM2Z2MnF5NlBDTDBXZ0Z3CmFPN241Si9pdlNxd3lIM3RwcXd6\nd3hmVUhKVXZvNG85WjQ2bmErd2NwSTQKLS0tIEJscHFsU3JROXRLelcxbEVpdHlF\ncGwvZ1E4OExES1J1dVRPL0V1ZERYK2cKUhR478mkXQNCbcr5KHMBm+IiDA/fQ9qL\nGVKFEp38q2BJ3VCGPQVNS1ttXA05PMd3VbvymTWXLBNQdjJt+g6qZw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-12-09T08:48:10Z",
		"mac": "ENC[AES256_GCM,data:9Clg9JSIGfLlhoA9TxAMQCftxW7+IaE5/js07OHqsz2EYnOOyREY54k3mxbVtuhiUU2ALWTY+gOswTvoITIMfd6jMA9wyfTi6AkuvVqSk7Vb5qFOQuQCNLqOsFHjGAThjaO47Olh8lG9I3gkpX2I6STD4w/pklqElH3z+Vq79wU=,iv:cYIq6QPcdZwYVPPi7a2Clqw7eQirdgcdmIS2vqPJvoM=,tag:xRZDBNwIhjJRmU0lnfea6A==,type:str]",
		"version": "3.11.0"
	}
}
