---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artem
  namespace: default
spec:
  encryptedData:
    artem: AgCd5wWpU0qISZnyrfh7oHpzblEq459eZfMX8pIhsCqviHsO94Z/SDohrlyQYx3OFCw9Ni52J5r+QT270/4V28ngaAldiR7NfZtveBZoHl1y1HVVHkpY8k8nirDHjXS2IJfsLX+rHIo2zNxfSJoX2wr6Xp7ZatIMPDgmwafCtiZTKLRFgOYqaAGjpdZ695LwlycWlvhfZs2LOMybMCGxlQhnZi9bFIcUvJ3n6sOwhdouVCkXz5ug7/xLkzAHnSmDV4ZS24Qs37d/G8ej7sroLln8CQ7wU2WvYrG2XLjsgQYK77KL1nIKQkdHnvHwlnZfIsWqW2f73B4VKw6vmaS8m4D1UTinIvOW1By2SxH6t93Erg4OnowSraMtfBUutTrUsU+MwmCc4Sa7j3dIDSRBD5+QzDFAoRmQ5zUVG/Kqc1P94FgqiZXA//+Q2q04+BAjPYopQTIybEEAK1AJWqroUIuvlbUstLrpGjhCnxBMsSv6f7K4NDc0ZwEIiX5bDfDab4lKgYvMeAXVE53ItDH33ZohRLpmQt7lCEkxd+fkK4+gu55dH7Rhwb2tGGuOcnYS6wSR9cvYP7pBioh27OIAojG25yt04mu/MPGVQxBe/Y3co0B+jVapDT4cVqJFV1BFwTe0ZnFBfw2/c4QDIj4gwvRnUYOXSp/DSuR/954hSWkl5m4ACooGbjDzJO1k/mLEtDTTKqk=
    karina: AgBUZ8U5OxbL46YrRXjLiSM8aku9IIcYoXPodRIwKcdzLMsdSYvrZnOaPYjUBAVj2nhqSAEfylvASY42Fhv/gclge7o+nWEmnFU17bJvP2/4R+MB/1NE7z8zDxa4w0yz5tHUaCjbknUrp7i7vMWKyrusYAB/oguY9yllGWpglZVcAhUuOJnIoGo8C87ZsUX7kA44nFV4LEiGmrz1oaEBlXS6c85jlzC5EBxK2QlhFjbu4YU1GA3SLU4Gt60s3IERKVn+9BIT9mgGEoINwjGepPm8jkmIbJeO/dEj3X6t21GEC/Z0b8PPdPfXM69U9wOksL+Jq9uiAtXoJPO61MoAXBXyKC5RU8ccsH14/cMTSZQJkulxltDp+YaZpI1P9hazN/arzF2zWdxgc6549V/7S4ylvsce8rDmbfqWX73KJI2bnrkA6E7HZfDmBiUNr0qlrKFK/ugXOFSWMmHYHUMV9IFHFgJXO+F1hD+Rhv9T5emz6cOVfFduruw+iGuctgSpMNYSRsFe0WJ8kxMNRavmFTBSjNUNlFBeypm8RzhYcg1Dsajb6qkMkf2Wo2sOZ4bY5MJM49Yn1w6qUIZ7uLpZSpBBjfLwMeaVfS84cGNxVg1BARHKPzJCB3djx0N3zxWHfnUaCgYnGLwp223Hz4qfZCFScTfHUo/iyfBPdiP4UVTF0s5KW/lgw4sIfoWj9aiQuzG7M8o=
  template:
    metadata:
      name: artem
      namespace: default
    type: Opaque
