---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: popa
  namespace: default
spec:
  encryptedData:
    popa: AgBgf4i/Q2YhmfKioT7eiEQUUo9h5kdjUEJx9UmJLRFpITSI5nz0nCSZVTyvXUw0KGOaS4/oWtyORrACby0mbURhiS/TR1kVfqplrwFDKdmnqktZ+Gif0Vj+iKZCVMl1nXUf1CjbQMYEH9bPUp8eWi7fts9GMTmkWwrLqaF4R290QjEBjuElaQ5djUWXwU4W7iZBFxc9/ADopssLIrpS25mmpEht4RmVn82noC5wRQ2w7f/mfEIYfxEHDjZ+V/pq4W63v28Zd8QTWjaN3Pmg8LZMZrmIBl1eGBKIWH1Pk86dN2xn/uHzKvKBQuRNPYThD7B2lFQamTQapJnbOBoWA4x3TiH49Ixnw85nWtgtX0uYpNfpAZ9LRAM8dNB/zRCUs1Gex3Ss4h/dGuV4qLiK4n5TijCIvxL1+r0W8MLaLdExh/tEHhSjW23mTY9sBhpYBPoqqs03YPXzn4bczbSCUYOZMevBugHfz545zc+z7tWufyzdOJUoebqe/YYFR/WfQ+/0SFHWDZ28R8O6jM07i+6piEW/1m12TFWZSDFYzHK/TKNx1FSIIzcclw9+Zp+7FpAIAGDM4BfozxFjFLOkt21LETfWJFYI0MBmFNh396dmJxeEQcGcy73WGoS+6mivIPIPdmRkAySLlLIiqwSTOToR9ovVfr8PHX9WdtmFS3/XffT16ZZ6w36bvV6vRIgZlXAuatBeVHw=
  template:
    metadata:
      name: popa
      namespace: default
    type: Opaque
