---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pupu
  namespace: default
spec:
  encryptedData:
    pupu: AgB0Mq3iUkQV3PEC9+VZnRERUVAgcfHg/U8FbY/XnHN2+53mbXAA5Duu+bjt2ssK9QAU8U/q6EG7UgYeGC6Bie4wezb4eP4ZJKXQtj4qD3HvyJ48gf5wXlMP3tnc+YzdV+iA/3SKTPRTTRKRX40HsGT/z3JAedGb9fzqvCCz/4pwjJKaN0PGlpLGTwdAKtzbemMeWByUEObI9JlasYcVbnHIwVJ+DOfJ/q3zN4XcmQiMPjZL0qKxHMriFf/RX+lNeHdxwUWVlOiw+wqAP+ZQJk/xdHfUXUuqXUb4c4ekibeoJl+NjsIhUIAC18HZc8NqIMLWedYzJfy4ID7pqGq3p16CXzx0IrvoKnqNunpwGX0zs4cNvd3TLTYNHowYUTMFWxWlQJq+CM03Gn5Y9X1LZirLbpjxOfiAERJtvN3q9/bHhZLM2QXtgriHxxIPFI+dHx0jCOFOOYGOtzLvfVxGVJmq9tGcyMH4GsbngUWRmGWU2pkpUthcS4aomytqr+7miGTUNDFVEMc1d8eBcvL7MXerMM2AUBGR3s4N650qsyG35TOE5ZRBQKIC6nAvFI2RrFWtmxsavmkQgKeWQ/v/Fl7nEKHIfrh6VOWRK27aoF05OTqOok6Pl13wDA3+bECEcQkukUXYScY4tp2ZPiaYDkosTSlnW7+3LAJTKuDmipwvhXGTJt3q4kpHkTnSJMKZWyLenIs=
    pupu2: AgAbWrhTxy013N5FJH6ANdcS79DzwegG9oavLPdjGbOpZ2W/5kKPJh7N7dzM/Y5Qt63ixoQ9Jsc4xVVF0fHmjjvvH792Hgf4fJljIx4Bu4aSs6ZJBSWoy5emII9OpyCR3g6Eq4gMdXrK4fFCKt6DEmMpdcrtGWEweEhEJEzrvf4fd8JOFGY0S2KiIF3C/A2myc9ZBhWy+EkShCXageyUESA5pvrYhgQ7RpgEU5aPFXg+5UVtOXHyehkBpFOibg3GhKEEiUOgGVBqXGHP2AqXRLRqJ+JMxpPb9CTr/spjxYBYfw6NhaDsOYSixY7VzXDB2Srf5+KfQY/u4eIANMY+hntk9+YkGC3jdNicFo+w1pufhgP89wOX0TkokO54uibE1PWImYiYJBMeM6SgtnDr83NNshxlosiSczLVDLh2NruaJaVr9ApRBPQ9LMg17Zemy61vVYOXEO9wEbfUudljrCo/Q7EdBMqk13FTWuWFVLP/SkMfdSz17D4HGqRGsD9ItrA8Q9Arqvnn1PdmD/dgoc9vcbsHZE3MnuePOMGFnQndo+LBzwXxCnkzzPXYtNQJVXaDLz+/ZZNt+Iw0WH0U92HAKJX+iCRMVnDM9bT5KOHo3Fm9xywnirjSadfWflI+whBm0O/iHWPHnlDJ1qQ20I+GeWIXvCAK21SqXKwNo8Pye1v1D2sugk5RcEGcvuqpr9/WjI6cqQ==
  template:
    metadata:
      name: pupu
      namespace: default
    type: Opaque
