---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db
  namespace: default
spec:
  encryptedData:
    db: AgBLTrz5hUy9SJoVaZxDr1dGBeYCV2kA+xKQ4bIIRaEtv/M+LD5grQqJggHfxJrO7EVX7kwBil/zEA08Fq4XkAfsXaq67s0jdi1oF21gjitCELGeXWemt7poJLvhLQ8n6ZAwPnBhaRwVFY5qE0mYBl0yBMPyN/TK98uiUW1HpXrybwuT3Kcoc2c4YFxAKrAtgBuBcNvKG9EmGrAFEAADTU7TKPU4ztjAIz3/gvzKOJ544Bf486UvHj80CbylIdIzavol/MS4qpUMu03jxZozdT4SLUhLizCzh55sxinQdNl/phPqA+a4WpBqS4TGUTzO7KAVgCv0c5u9Heu4cwv93S8wKbFWATYbkeyB+3nD2QPm74JCgDuaEZEPDEdBBAV9kXv8VLf1QS2eDQSK7NNJ1YCk2kl5ZoK12++GzMwWiQD2ulWOy49Ecw7dd3ygTHDvgYudVaoQTQanygAwtN2njVin7GWMitYggwTGtwM2X/5ZTIbXfus/vvM7BbwdTU8X1S3Oze6ZvNMcil9r49LUHWnski3jLrjmBMqxKjidoGH24kJIwpolSUsPtn9g1p0qCnmpPJxWOiEwXvh1o+C3v0VuwOAXB6a5JZq5/NznDC6BEjwf8GSMo/V7GWs5lUVoarIQdNFcEsJ3rmGJe5EHwdh66WsRBS1cmqhjXauaytfNjE9wcPwpBO0wlkpaB8OAfI61GJg=
    name: AgBpqPLiBtMS30AK7drnhduE8wzyyK4PXiCZNPSY3OWYkqVlAxOZpNOWJFlMDi5BGirgznAvW/kxkalGvAImtJQmTzmNpdHyvrePSdqpzFGIyIZv532iwOUK0Wdm3pAc60nFz0Kl4i9Cg9aBct9DMiDFrMbPK9oPlVgINjIQBnvkj5YfKjNSIGI9ReW//2Za1ObtVzl9gZJhVdkHxKXY9n4tawHGGeCOOMQYsj73rugVA5TBA5QEkE6367km+nSI1+O99RkUPS40NnSMZ/6/QPL2A2plW82WBh7hc09IMTcm6FzpWAYmYNVpwjZ9qivLBrM7aJNaNNmlck6OyxfwDrxMtBB2lJIYAKQahJkx7jdzjfZOxMmWMCFztkgMLNxBUZirWOMSvfKyZTlK3/yretGK7V1tTUKNEdy5FGPLz09unlGKmrgAZKkj/HXltfBw3vzDTjlvQSt3D3dxE0SBWAhaVheBYZvvxQUDULcsdWEzN0Q/LJY+nH3pNyuvOHtOqEicXsMAN/5KSKCFawxulnB7DyA4SUW4SLJDjyUo1DBwRNf4LYWPulJro0F1XnYShvNd2yN/oog491i0EQ9IMgYjbJ8NvZPlxSCXU1hMEtIJIrwX7oHhE82EGM/5rKMl3TXH2eoZbjSKhNaJvuOMrhoWs8ifqjsdeI0hGxVtBw0IUtDiSNzfZEWRRCUBXko4CWnsX3QC
  template:
    metadata:
      name: app-db
      namespace: default
    type: Opaque
