---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artem
  namespace: default
spec:
  encryptedData:
    artem: AgC3TlKDjHewJ3M23BxJ1CClYuhkjNybJGWB+tNbb95ECGADVBsWgBw9j9SxiW9SavgXX/PMOEeW/s7t1SSTRnsBX9Tk6QzAXXh58mkD83GmF3GCHDPK3QXBI2eFs7GHoFIFX++RXpQcnBftqiy7k0kbChx27q8zBFC//ncNxeUsCeuWdfMwZIVkk4ByBwd0GCrFFJ23/QHm4QQI7fc3g6CDE+suicOuA4CTML/InxyzQvPsW4h+d+yoh22NU+grz3Q57VPxYdiBsLBujUjVKhIoL+xxIWtyb6hPLrlwLYTznUyBeqng2jgqG6ms5MB1ID+FA+10eyx5zcilzZNe/0Sc4bYrwReoIGlJdirgPH1FI5ToLJvDrJaB6i4ulPpRDREz5sg1bm3E/0vNzTRawytBygrjvRIP+O4+R/Qeg7QmDQqxDfeHKuc59kNaUplAZ6362KiEePE8RiMyUM9qAmZZ9JApGIJ43WEM1PFuDpqXTMCNwahbEn6eGzeHbmbNhTRbEUTIs/W8r5dQ1u3doyjownviDwp1uuRRGhMliKbo8aoHHQtMu0MolWq1rHzguTLupzedD4D6ySQLqmdjPuGBAeI7wjR/VHQCOKkO5k0WUO1FcuArNQ9+7PMh4NWCpNUmtbQfbmwrYjoeu6FzgjYYsn3aSBwsgPJaJ4D8sSMBonOPDoQXTDFwREYptsIZLxqojeKT
    popa: AgAc2nNjTX2ZNUzVEDMZh4BSZv7VRqTznx2+u4cAKrSiGsMtRvQuy3eGIXSjaWEd9oY7mmVwV4W+Nw6HtPDeqZhkRyOPBTVHA8z1OxtZWvMU+YSll8MaHqPhMcx0CFj6jAo45oq7/Rls8AbFLF1YA8cDKTOjb1Cew0OAJq52fFaYnyos04TULWoOmeWKC2parqFmBiKmY5isU6QN6ZGIvamJKlIbNHoZOm6Iio/BdxuR5nXP2qrUM6KWV1ElE5prZDXU3nSB88KovXa7fVSby9RH8ljrM50u036AnpL9gNRNY3uXXZU757cNLxqdYyoB18KZ4rzjw9oVAt7cVYozYdd5TXfwD0Yjzglxyb01qcQAwVbzaU9x4ocphgMUHGMJYZ45R3CD3BHKXaOu2B8YyjpUvl44IM0C69OCpzsXcUTeyGtBaTYexys+cXaOvbNNupKUSikeItlyT4EszscL+spQuzw/1IcOmWOAViFVYQZXlD8PSCPSRX3RNVSibgf4vSRh+/SGjffGo8L1B2xJ9635j1vb30ld26c9gunRxcEPsMXknMl3yf3QnRvNxapFQHT8J8l8Y/CWawLiQLBsGx/+2nlp+aM5AeEibGdt1ueyoyrRAmP94Ur0k7sh0K4fun2nNusod5AdjvjZEOpeGxipAEwaTpdxfobhLDehWx5FB0ACXhPg1MrHHtXlAiUVD6DiyG7R5LAv
  template:
    metadata:
      name: artem
      namespace: default
    type: Opaque
