---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karina
  namespace: default
spec:
  encryptedData:
    karina: AgCytNXrQeob6sP68uDV5ESumJn0CWEGZYmkGWLO/X28V7R8GedyDLGtOKF8QjE0MTQhuUS1e4cKb0uZCN+PiaArfJ8GBZaZqjNifXcOMSpMUt8yH30sZp08tdX9pFx+/bseMqdT5clNzqf5ZV7yrPsYty4vneURSCUC25hQ4IB1aZNbkIpmbyy0y5X5Y4mjbn/WcmdpUoihZk5LgFxDHdGJuFKnHX8Vh/10hInknOcYfH/3w7v4OHWnW8/sJxIA3vXA9CNi1oXdW8GmeIgfBfUKmXWKpqG2gXkuKQr5jHka/w53oc0SojZhIt4Opa3GwZPOgx9176alVI0c8gK4R7VoIESHVs5Rhmp71UgocK3pURbYvDzXYxGPd9Cexva3MyzBVsssuGbjp4RBiTUVAsAERnCJnUJIQaHn7xlc+3yE/7k8gxoI6ejllXaXpfFKBm5dwtXVNzTf16P4v3P49HXO6DAqs1JrHg8dmQhrdtfi3FYvMhutkSeV74DL4Mv8VlgZENTgBQeo6SXhkX6KWnCvp1fQDmJkih9/UDHWHY4lKa/BW3szDZeOkotiyGJlFOrHaop0qeLG8cxMXsEQXRy0A3D6jXlOFfi122YUmJTh1g+axZrwxIYJeUiWXmU5ugqcORAEx3xSVWaM2TIG1g9fWdfwHdU1EQVDZquArh5G+2O7TxuWrKtsceq32Yv91pzPHwQ=
  template:
    metadata:
      name: karina
      namespace: default
    type: Opaque
