---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: na
  namespace: default
spec:
  encryptedData:
    na: AgAbACrPQ2MQelGNZeYmBfyDQYAXWwWA5WBKRDDnV7n8/Zxwle2aQWLjoY8Fb2Jn8g4Ha304NqUn+lPEl/UdICSYbBdN5oguGCzsi8U3I9GE9B2OwQfeh0t1i74DBcZcVm/2eZ3SztP08MusP6Wj2bKZhBhv7hiYPYy2DWE/yEV52xewWpwzYtVRMeXHXZNvcU+6wHv6hBZ8csNOqwj7gk9d65CWYObatx/tOJ/8JH0DDAkR3ypnMFi0IJCx/E+OMjwxyKtJ7LGzL+Gfix6O2iSUJ6TlxuhNNV1yWTHC7YAdoR+ewUJDBI9An5txo+sNZvO4UXiCioLDMQ798cS7Xjyg+JNmtZJNglR044P52FBcLh8kpQRP9xMAQoqAOxs9LMb52hYW7QGA5tCgVqfQ5tWggB3UncWie1XExlL4oZ3uNDJEOhF/ic3fttiluMVxuVZZaIIHofHq9WxFbRnsbghpab1mk2uRcZdqB/CMYTY7su8XCf8YbqbKcFlRveIA9UUEfDRi9phwt2J1Pf/lqHqlYSXr7RM/ABgyikiaQOnbeHyLG6POSprr4chzOlJ29Plyjkl3pzCroYUzDEHYYRd0AbtV+OzD2cJqva0cadDHyHF17+MWkOIVTLFpW1T97NQb1quvD7qagUzcPL8to8N0PZJb6r35qy+SsjecHE4H/BpcV1ong2UhvBTsj7MSy50k+g==
  template:
    metadata:
      name: na
      namespace: default
    type: Opaque
