apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
stringData:
  root-password: vault://secret/data/mysql#MYSQL_ROOT_PASSWORD
  password: vault://secret/data/mysql#MYSQL_PASSWORD