apiVersion: ENC[AES256_GCM,data:uOI=,iv:XJCAOT6+itmYdaQuR8YyO8VmEtulyN5nkZmNq14LElk=,tag:rXzh1zT/Gx3q8ATa6sdelg==,type:str]
kind: ENC[AES256_GCM,data:3Csv2Iqc,iv:zzxYhkd3BhznfWhyeiuHiACLKkScrS3lfEtf+WScPh4=,tag:3hFe1YFe23zF51WuV/Nt0g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TDxFkYy8,iv:Hp955gWTzrH9v9A5DIcFBjgxcymKPn2KsDPRQkzRsck=,tag:JU8Yy9+5BF+9WgFNgzSiXg==,type:str]
    namespace: ENC[AES256_GCM,data:v6lUNEMpHA==,iv:/mjIqBe8Ths7Bm5ViGPi83LJFC2tVrECytXycShIydU=,tag:vm+JtWxzbC/EwjNRqF621Q==,type:str]
    annotations:
        vault-sync/path: ENC[AES256_GCM,data:67SQVxRSz+Wv2uTcYjEhUsdfuyolsK3O+w==,iv:ujJs5kpn6LL+/m/dCQDHPo8rPxD0CL6pMJZ3PlKvkN8=,tag:9EJ/rXIh4CKbg11zKdCtKA==,type:str]
type: ENC[AES256_GCM,data:PzX1mHBA,iv:H7qg3mU+hoIjdU8GNUkVegHA6mjrZz87jkBaC+JD+So=,tag:tfdh60AnxEoJyKv3mj8H9A==,type:str]
stringData:
    рф: ENC[AES256_GCM,data:avs=,iv:vxnRw4iV1xrzXuuhTX22XvKAWojy5Z/EMjuG+vdjWuY=,tag:pVAfJFetwuJeaOoJT6+HUQ==,type:str]
sops:
    age:
        - recipient: age16q9p72g5vqzj4p97qfuzfkqvympwhyk9kl0rs7wksqexgj7fyp2shvwmya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW40eE5hbkJCM1JuWmNq
            Y0p4bC85Y1FHcC9ucnZ0L0QvVHlHSkFvQ1hFClBqM3pUYmNKZThjMklWOU9XWDFr
            alJyUVMwbG5NMTY4cXRiUFNSOXRFSjQKLS0tIHFEck1nVEFwemlhTS94U3lVMHdn
            cjNHVGlkcjNBSU1PY1NYVjZQd0ZCN00Knxsl7g0isqwnMWghr7WwuHAiFeb15gQv
            YRdKX6TzBA49gO0bbc8PBTDIZOfrO8zWeQkYvJ92+YAgL4OEcLGyXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T14:48:34Z"
    mac: ENC[AES256_GCM,data:nFaKGxAbJHIK9UdMRDZKDOZ0WxocIDBG4sYcSaBW4eBoMOjl76LdlUTggQY5SzaQwz+WJHD52WMLovZA6ugK74ggsetNLPpJIojCBohaUbVaC102jJTfyXCKJvN/M6rCBDHrkpjwIellIkIYxAHWPv3XBWqy+qL+2ourl3ibbCA=,iv:3xJESJ74BkHRpXIT2n1OIqLUBhyMoGijRvJDA6na9v4=,tag:hSu6M4leJDI9uF5ypbfraQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
