apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-sync-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:artsiom494-lab/test.git
    targetRevision: HEAD
    path: sops/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-sync-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true