{
	"data": "ENC[AES256_GCM,data:lHftaxUd3rAQmKvO63mZ8Q5QPD5vpJ2mdiDcmcjlgaUxf4JMyFknNdUHoqABIRIdEeYftdhK85nLOGq1N5DUvKn3kF4S5B46A6TaVrkVUuPUZA2Sn741uZlQmyJ3+oUJ+84D1NXh3WLrqy0VQNDk18uLzYJw2tNkyE9fEcd4Ah6kCynS/sv75Iu/wIsDlPuvIkMIXAJY84DeyGcrLyyeBjKI5m8yL2lVxyPNVpqiaXl80Bul/XkqDUBz9yb2kYY=,iv:GHtYjFsTXqip/2FmzmtIBDx+y5894Jsd45zX04Wh16Y=,tag:id1kpkGWbMytepMTnR4UxQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1ugpm2ngs9exn42wdw6r3wwru2wu9mcq3pfc9yjtvh47js8rcvsgstkaa3h",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS1JWaXBMSThQY3hpbjll\ndllqZk1aOEFGTmY5SHlYVVlKK1RVQ1NIZlhzCkNrd0RPTEQxbDl3SmxzLzBRYmxX\nanNnK2VENnV2b242MGJUQkgwZytqU28KLS0tIEg2VFNjTVVWbG4wK0RMR1lUbzEy\nK3ZzTnZhUSt5aXRaNC9NRmZadnV5QlkK1eTdvKjOxQF3KCT3xDFcHhcats91AM/s\n69iVG6BJwMV33p3Z46T8uKGE9ACs/oxIKXtZzPKsx+0MLOoun07I+w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-12-09T06:34:12Z",
		"mac": "ENC[AES256_GCM,data:VmukhtgMQD2rDDSkT+M+psGkQ2JHM5lP50LfOtckW8IPTU8nHTEhUJXCDQWz508Bsn97YXTaYrHesk9cb599guChzGbaCrwI6vIkhAAdodZEgTXB5qJBUx5hFcHdksqwkcgLG8Ehpn7m3Vbxqz36b53RokHw/nbKTiRZ9KmpY9U=,iv:ayqBtZR30vsDZ5X9Nhq9h2jK4WCdNV2zeF3OQI9fZog=,tag:SLaysGqj3T9orD1un6gSHw==,type:str]",
		"version": "3.11.0"
	}
}
