apiVersion: ENC[AES256_GCM,data:i7M=,iv:sdW2IhPnmcD7eHdSGMx+powp/YZZhTfA/qBKP6332ys=,tag:CTrc+GWGxzxx8aIPHnJd9g==,type:str]
kind: ENC[AES256_GCM,data:hXsCHe8h,iv:mrSqlYpWWb6NmnEoycIC5FrVyB+B3Gi2T9cZWXfxSXk=,tag:EU3uuzAl6Rn5p8PO56JMfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W02PYwL0,iv:xiCccu+RK4wpUf3kCfCGFw2tvm1dJO6RXbd2PtVHClM=,tag:9vOgrkVFwJQqB6riy18LRg==,type:str]
    namespace: ENC[AES256_GCM,data:emj7MNfRVQ==,iv:NigbRKVPy6U+vmMVy435JZ93W3JEHJsGtnN7S7Ygovo=,tag:FjltkN8fk2y1Zod0XOd5sw==,type:str]
type: ENC[AES256_GCM,data:NV5G06vo,iv:KiAXIEScFjgKICo9XO1Xb8jZyO1YcxYBNFjkGWvMHhk=,tag:5txxH583HZNJtabCCdf4dA==,type:str]
stringData:
    ya: ENC[AES256_GCM,data:d/JS,iv:42HxhlOr/Wcc/Zo3c1phX6pM6iyAUMP2ZurBghXsAhw=,tag:OeewQ0xOsejstEoOC3qL1Q==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.vault.svc.cluster.local:8200
          engine_path: transit
          key_name: sops-key
          created_at: "2025-12-08T10:36:47Z"
          enc: vault:v1:r/pwYM8lVZcC6ukhCVvqljsekU4rsgt066sIM4JO6Z1rn0gP5Nd/zILQXrtOve9/OwuqQe/fI7joQlR6
    lastmodified: "2025-12-08T10:36:47Z"
    mac: ENC[AES256_GCM,data:tAUUWT+wT45pNYJqzmbPlp/nSsJqNtXOTe9q+u5msUprQLHXcl6R9U9cgOo+gl6koRiZxwkg5KflwcWSIZIX3yqPQG5dhuE5VxP2EMPFrdzfwSLIYkZWLIwMF9Rqz268Pn/jnq1dFJC8MXeZgQoYnSjP92In3fY17XkvzcXwHmw=,iv:8kCxN0Brx4w6sZ7Ul9Q0I6AE3SSqyuBzswlC2Sxh418=,tag:2ocn4x0O0SQpXraLnvD4SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
