apiVersion: ENC[AES256_GCM,data:MwU=,iv:Yn+T93ZWVxafko6vQ+/dcDyrDf9gXgPTIfhaoXbgGn0=,tag:oFNKaHpXI0ChhKrv4nwa9g==,type:str]
kind: ENC[AES256_GCM,data:x0AMNBwM,iv:ovjn/+DrQz7O1YJKkS1YSjoeZgqAPpBaBDtCiXFL604=,tag:E7u4vkgOXEK5KALqVOCm8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:72yzLuoB,iv:YQd0FjF9rTlsGk7NcfcVY9LcSb4J4nSvs0oc+Yyvtj0=,tag:J6Dnd6E2I3FRgZiyLL6uow==,type:str]
    namespace: ENC[AES256_GCM,data:2shDWux66w==,iv:HESXCWnEUohEqLBZ/5ELxoHELnjGpJoeGMRY5NZP8Ng=,tag:AXwVEzNUiBQSqYYSTuKBOQ==,type:str]
type: ENC[AES256_GCM,data:u2YIfWzX,iv:htfBwkFzJgHDoakMuTIHid5/ilGbiztL6SE/G1AveIQ=,tag:OJ+XzmkJRodTqLIxTYTbcA==,type:str]
stringData:
    db: ENC[AES256_GCM,data:yY0gSDE=,iv:uAE+Yjwt2rVWnSJzXc0mZaSmOuqpW0V9J2+v1ZCQDLY=,tag:+idIw1wLwUSi3uMupg6bGQ==,type:str]
    prod: ENC[AES256_GCM,data:n6jZJp11,iv:EkN8u27nK7wVHvyjOKxrau7nZCKybVIayBoI3+P2GHQ=,tag:a3NOEev6518n1KNSccx1QA==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.vault.svc.cluster.local:8200
          engine_path: transit
          key_name: sops-key
          created_at: "2025-12-08T10:12:22Z"
          enc: vault:v1:wppE6n38ThYcKojXkXxP3Gy9eBeGqo/V5TjowzNOdsyN99PbAo3xuTTTQh/FMAdy9djCiJU2B2IZmNFs
    lastmodified: "2025-12-08T10:12:22Z"
    mac: ENC[AES256_GCM,data:izaFu/m1QVmkhrsz3n2OF2qZHFVspw5ZQ/OjDvLbMZ2nTKixLRJEhBne1w6tcmzyz2cp050fLcxPC7WPeEY+HA+T3yagKm3TiTxpXEszU8A04AJrJCZHHmOTY2dMblchGCOEuyidBRvWfINkRaLGQ9eeEAi4DihRIwTz/Lt5qJg=,iv:J7PCxNy1e0cS7sWik7rHfaD55kQvGCH4/gIfNnxVnXI=,tag:85vchF478/b3gZnm9ssZCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
