apiVersion: ENC[AES256_GCM,data:UbE=,iv:Rn+6WQT2FuXDmTZnSgC3oe9JPy3qmc82Jm87ATv7wmM=,tag:1pFg+PMybqSBRwntEKz5FQ==,type:str]
kind: ENC[AES256_GCM,data:m7AHIDCK,iv:C+i0TSzQ1FtYzOrKKUsCDw+/0gjU6GnX1DxP5yZoQ7E=,tag:mS639bZTFWFGQWSbYOqMWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nawKNWgu,iv:OWtjUDXKfCMPHSiKk5Oq/LFz8pAvHEcSF5aVaVhJjKk=,tag:J5XqYtM7l9GVwocQm+uYvA==,type:str]
    namespace: ENC[AES256_GCM,data:4QppMNyr1w==,iv:JPglgn9UVdnH5i0mghf3JFMC0wGe2Wde2T8bxrQAgLA=,tag:V1B2rSFT8aEbTIdIMvdw3A==,type:str]
type: ENC[AES256_GCM,data:Sb14SjwP,iv:jlWf5vM421Vdj/vzmxLPk8+sEK9Hf2H44iw8oa+c058=,tag:VyndL0KDuXFYbaTzkW7goA==,type:str]
stringData:
    artem: ENC[AES256_GCM,data:2FO3CA==,iv:9WnOY5BFrz/S04AnB2qH6Ap2sb3Xv410wqWtYzZAE1E=,tag:xkHiWqpXxt0DsR3flcaVaw==,type:str]
    karina: ENC[AES256_GCM,data:QdMJuQ==,iv:Ze4WSIqs8Ds33jD3ngyk7MH7vRayov9ZnlqC+TCXWm4=,tag:Nwww3mdGjmHUR3V04dnYkg==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.vault.svc.cluster.local:8200
          engine_path: transit
          key_name: sops-key
          created_at: "2025-12-08T10:27:14Z"
          enc: vault:v1:H7oCC+mm9L1RxZkJecszEMp+uVMw9LTyDRxMiwmfE7CjUhCdooic5veh4po4EaGT+0kmH8sOoCXLzT6U
    lastmodified: "2025-12-08T10:27:14Z"
    mac: ENC[AES256_GCM,data:plcrtWLmniUFZyUyuFmNok5NQ32mWzFgZGX8poECbAaWOX2aOZ3EWymsBe1chvpD7qg39nkHEyFAKxXnYs6Onm1sXsSp4lSmJYzuwZVA2cz3TFdN04RjAbjzBGbt/EZ9JNSiIh/mS5EBYGZkGm1PG++aCl1FUm6v/P05icj1OTA=,iv:Or0S+O4wdBz13AgkviN/8kOKm8U/bbh3Ab9p81iYkuM=,tag:T5YXG8juqKKsYTa7tWHJXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
